SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN ('Lima/Limao','Morango/Limao');

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%Limao';

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%Maca%';

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%Morango';

-- Morango/Limao

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE 'Morango%';

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%Morango%' AND EMBALAGEM = 'PET';