SELECT * FROM TABELA_DE_PRODUTOS;

SELECT ROWNUM, TABELA_DE_PRODUTOS.* FROM TABELA_DE_PRODUTOS;

SELECT ROWNUM, TP.* FROM TABELA_DE_PRODUTOS TP WHERE ROWNUM <= 5;

SELECT TP.* FROM TABELA_DE_PRODUTOS TP WHERE ROWNUM <= 5;

SELECT TP.* FROM TABELA_DE_PRODUTOS TP WHERE ROWNUM >= 2 AND ROWNUM <= 3;
