SELECT * FROM TABELA_DE_VENDEDORES;

SELECT * FROM NOTAS_FISCAIS;

SELECT MATRICULA, COUNT(*) AS NUMERO_DE_NOTAS FROM NOTAS_FISCAIS
GROUP BY MATRICULA;

SELECT NF.MATRICULA
      ,TV.NOME
      ,COUNT(*) AS NUMERO_DE_NOTAS
FROM
TABELA_DE_VENDEDORES TV
INNER JOIN
NOTAS_FISCAIS NF
ON NF.MATRICULA = TV.MATRICULA
GROUP BY NF.MATRICULA, TV.NOME;

-- Exercicio
SELECT TP.NOME_DO_PRODUTO
      ,INF.CODIGO_DO_PRODUTO
      ,SUM(INF.QUANTIDADE)
FROM
ITENS_NOTAS_FISCAIS INF
INNER JOIN
TABELA_DE_PRODUTOS TP
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO
HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;

SELECT * FROM ITENS_NOTAS_FISCAIS;

SELECT * FROM TB_PRODUTOS;

SELECT * FROM TABELA_DE_PRODUTOS;
