SELECT * FROM TABELA_DE_CLIENTES;

SELECT CIDADE, IDADE FROM TABELA_DE_CLIENTES ORDER BY CIDADE, IDADE;

SELECT CIDADE, SUM(IDADE) FROM TABELA_DE_CLIENTES GROUP BY CIDADE ORDER BY CIDADE;

SELECT CIDADE, SUM(LIMITE_DE_CREDITO), SUM(IDADE) FROM TABELA_DE_CLIENTES GROUP BY CIDADE;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;

SELECT EMBALAGEM, NOME_DO_PRODUTO FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM;

SELECT EMBALAGEM, COUNT(*) FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM ORDER BY EMBALAGEM;

SELECT EMBALAGEM, COUNT(*) FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Laranja'
GROUP BY EMBALAGEM ORDER BY EMBALAGEM;

SELECT EMBALAGEM, COUNT(*) AS NUMERO_DE_PRODUTOS FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Laranja'
GROUP BY EMBALAGEM ORDER BY EMBALAGEM;

-- Quantas vendas foram feitas com quantidade igual a 99 litros para o produto 1101035?
SELECT * FROM ITENS_NOTAS_FISCAIS;

SELECT COUNT(*) AS QUANTIDADE_DE_VENDAS FROM ITENS_NOTAS_FISCAIS WHERE codigo_do_produto = '1101035' AND quantidade = 99;