CREATE TABLE ALUNO(
    COD_ALUNO NUMERIC(7) NOT NULL
   ,NOME_ALUNO VARCHAR2(50) NOT NULL
   ,CONSTRAINT PK_COD_ALUNO PRIMARY KEY(COD_ALUNO)
   );

CREATE TABLE CARGO(
    COD_ALUNO NUMERIC(7) NOT NULL
   ,CONSTRAINT PK_COD_ALUNO PRIMARY KEY(COD_ALUNO)
   ,COD_CARGO NUMERIC(5) NOT NULL 
   ,CONSTRAINT PK_COD_CARGO PRIMARY KEY(COD_CARGO)
   ,NOME_CARGO VARCHAR2(50) NOT NULL
   ,SALARIO_CARGO NUMERIC(15,2) NULL
   );