SELECT DISTINCT
TC.CPF AS CPF_DO_CADASTRO
,TC.NOME AS NOME_DO_CLIENTE
,NF.CPF AS CPF_NOTAS_FISCAIS
FROM
TABELA_DE_CLIENTES TC
INNER JOIN
NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF;

SELECT COUNT(*) FROM TABELA_DE_CLIENTES
